version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./app:/var/www/html
      - ./docker/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    links:
      - bancodedados
  bancodedados:
    image: bitnami/mariadb
    ports:
      - 3306:3306
    environment:
      MARIADB_DATABASE: bd_app #Cria o banco de dados
      MARIADB_USER: user_app
      MARIADB_PASSWORD: password
      MARIADB_ROOT_PASSWORD: password
    volumes:
      - ./docker/sql:/bitnami/mariadb #Persiste o banco de dados
  phpqa:
    image: jakzal/phpqa:php7.1-alpine
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    links:
      - "bancodedados:db"
